---
# Insert new cops alphabetically

# We want Exclude directives from different
# config files to get merged, not overwritten
inherit_mode:
  merge:
    - Exclude

require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Standard/BlockSingleLineBraces:
  Enabled: false
