# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(File.expand_path(".ruby-version", __dir__)).chomp

gem "rails"

gem "bcrypt"
gem "bootsnap", require: false
gem "fast_blank", platform: :mri
gem "jwt_sessions"
gem "oj"
gem "pagy"
gem "pg"
gem "puma"
gem "rack-cors"
gem "redis"
gem "strong_migrations"
gem "nilify_blanks"

group :development, :test do
  gem "awesome_rails_console"
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "factory_trace"
  gem "hirb"
  gem "hirb-unicode-steakknife", require: "hirb-unicode"
  gem "isolator"
  gem "parallel_tests"
  gem "pry-byebug"
  gem "pry-stack_explorer"
  gem "rspec-rails"
  gem "ruby-prof", ">= 0.16.0", require: false
  gem "stackprof", ">= 0.2.9", require: false
end

group :development do
  gem "database_consistency", require: false
  gem "brakeman", require: false
  gem "bullet"
  gem "bundler-audit", require: false
  gem "listen"
  gem "ordinare", require: false
  gem "rubocop-rspec"
  gem "standard"
end

group :test do
  gem "consistency_fail"
  gem "fuubar"
  gem "shoulda-matchers"
  gem "simplecov"
  gem "simplecov-console"
  gem "test-prof"
  gem "webmock"
  gem "zonebie"
end
