# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby File.read(File.expand_path(".ruby-version", __dir__)).chomp

gem "rails"

gem "anyway_config"
gem "awesome_rails_console",
  github: "xunker/awesome_rails_console",
  branch: "pry-0.13.0-compatibility"
gem "bcrypt"
gem "bootsnap", require: false
gem "fast_blank", platform: :mri
gem "jwt_sessions"
gem "nilify_blanks"
gem "oj"
gem "pagy"
gem "pg"
gem "puma"
gem "rack-attack"
gem "rack-cors"
gem "redis"
gem "strong_migrations"

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "factory_bot_rails"
  gem "factory_trace"
  gem "isolator"
  gem "parallel_tests"
  gem "pry-byebug"
  gem "pry-stack_explorer"
  gem "rspec-rails"
  gem "ruby-prof", ">= 0.16.0", require: false
  gem "stackprof", ">= 0.2.9", require: false
end

group :development do
  gem "brakeman", require: false
  gem "bullet"
  gem "bundler-audit", require: false
  gem "database_consistency", require: false
  gem "letter_opener"
  gem "listen"
  gem "ordinare", require: false
  gem "ruby_audit", require: false
  gem "standard"
end

group :test do
  # Disabled due to https://github.com/trptcolin/consistency_fail/issues/34
  # gem "consistency_fail"
  gem "fuubar"
  gem "shoulda-matchers"
  gem "simplecov"
  gem "simplecov-console"
  gem "test-prof"
  gem "webmock"
  gem "zonebie"
end
