---
name: Lint Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  brakeman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: brakeman
        working-directory: ./backend
        run: |
          gem install brakeman
          brakeman
#######################################
  fasterer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: fasterer
        working-directory: ./backend
        run: |
          gem install fasterer
          fasterer
#######################################
  bundle-leak:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: bundle leak
        working-directory: ./backend
        run: |
          gem install bundler bundler-leak
          bundle leak check --update
#######################################
  bundle-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: bundle audit
        working-directory: ./backend
        run: |
          gem install bundler bundler-audit
          bundle audit check --update
#######################################
  ruby-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Ruby 3.0
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x

      - name: bundle audit
        working-directory: ./backend
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec ruby-audit check
